#include "renderer.hpp"

#include "log.hpp"

#include <cmath>
#include <cstring>
#include <string>
#include <vector>

// Dynamically load vulkan-1.dll so the Windows SDK Vulkan headers are enough at compile time
// without a full LunarG SDK install. Link-free.
#define VK_NO_PROTOTYPES
#include <vulkan/vulkan.h>
#include <vulkan/vulkan_win32.h>

namespace
{

struct VkApi
{
  HMODULE mod = nullptr;
#define V(n) PFN_##n n = nullptr;
  V(vkGetInstanceProcAddr)
  V(vkCreateInstance)
  V(vkDestroyInstance)
  V(vkEnumeratePhysicalDevices)
  V(vkGetPhysicalDeviceQueueFamilyProperties)
  V(vkGetPhysicalDeviceSurfaceSupportKHR)
  V(vkEnumerateDeviceExtensionProperties)
  V(vkCreateDevice)
  V(vkDestroyDevice)
  V(vkGetDeviceQueue)
  V(vkCreateWin32SurfaceKHR)
  V(vkDestroySurfaceKHR)
  V(vkGetPhysicalDeviceSurfaceCapabilitiesKHR)
  V(vkGetPhysicalDeviceSurfaceFormatsKHR)
  V(vkGetPhysicalDeviceSurfacePresentModesKHR)
  V(vkCreateSwapchainKHR)
  V(vkDestroySwapchainKHR)
  V(vkGetSwapchainImagesKHR)
  V(vkCreateImageView)
  V(vkDestroyImageView)
  V(vkCreateCommandPool)
  V(vkDestroyCommandPool)
  V(vkAllocateCommandBuffers)
  V(vkBeginCommandBuffer)
  V(vkEndCommandBuffer)
  V(vkCmdBeginRenderPass)
  V(vkCmdEndRenderPass)
  V(vkCmdSetViewport)
  V(vkCmdSetScissor)
  V(vkCmdBindPipeline)
  V(vkCmdDraw)
  V(vkCreateRenderPass)
  V(vkDestroyRenderPass)
  V(vkCreateFramebuffer)
  V(vkDestroyFramebuffer)
  V(vkCreateShaderModule)
  V(vkDestroyShaderModule)
  V(vkCreatePipelineLayout)
  V(vkDestroyPipelineLayout)
  V(vkCreateGraphicsPipelines)
  V(vkDestroyPipeline)
  V(vkCreateSemaphore)
  V(vkDestroySemaphore)
  V(vkCreateFence)
  V(vkDestroyFence)
  V(vkResetFences)
  V(vkWaitForFences)
  V(vkAcquireNextImageKHR)
  V(vkQueueSubmit)
  V(vkQueuePresentKHR)
  V(vkDeviceWaitIdle)
  V(vkFreeCommandBuffers)
#undef V

  bool Load()
  {
    mod = LoadLibraryW(L"vulkan-1.dll");
    if (!mod)
      return false;
    vkGetInstanceProcAddr =
        reinterpret_cast<PFN_vkGetInstanceProcAddr>(GetProcAddress(mod, "vkGetInstanceProcAddr"));
    if (!vkGetInstanceProcAddr)
      return false;
#define L(n) n = reinterpret_cast<PFN_##n>(vkGetInstanceProcAddr(nullptr, #n));
    L(vkCreateInstance)
#undef L
    return vkCreateInstance != nullptr;
  }

  void LoadInstance(VkInstance inst)
  {
#define L(n) n = reinterpret_cast<PFN_##n>(vkGetInstanceProcAddr(inst, #n));
    L(vkDestroyInstance)
    L(vkEnumeratePhysicalDevices)
    L(vkGetPhysicalDeviceQueueFamilyProperties)
    L(vkGetPhysicalDeviceSurfaceSupportKHR)
    L(vkEnumerateDeviceExtensionProperties)
    L(vkCreateDevice)
    L(vkDestroyDevice)
    L(vkGetDeviceQueue)
    L(vkCreateWin32SurfaceKHR)
    L(vkDestroySurfaceKHR)
    L(vkGetPhysicalDeviceSurfaceCapabilitiesKHR)
    L(vkGetPhysicalDeviceSurfaceFormatsKHR)
    L(vkGetPhysicalDeviceSurfacePresentModesKHR)
    L(vkCreateSwapchainKHR)
    L(vkDestroySwapchainKHR)
    L(vkGetSwapchainImagesKHR)
    L(vkCreateImageView)
    L(vkDestroyImageView)
    L(vkCreateCommandPool)
    L(vkDestroyCommandPool)
    L(vkAllocateCommandBuffers)
    L(vkBeginCommandBuffer)
    L(vkEndCommandBuffer)
    L(vkCmdBeginRenderPass)
    L(vkCmdEndRenderPass)
    L(vkCmdSetViewport)
    L(vkCmdSetScissor)
    L(vkCmdBindPipeline)
    L(vkCmdDraw)
    L(vkCreateRenderPass)
    L(vkDestroyRenderPass)
    L(vkCreateFramebuffer)
    L(vkDestroyFramebuffer)
    L(vkCreateShaderModule)
    L(vkDestroyShaderModule)
    L(vkCreatePipelineLayout)
    L(vkDestroyPipelineLayout)
    L(vkCreateGraphicsPipelines)
    L(vkDestroyPipeline)
    L(vkCreateSemaphore)
    L(vkDestroySemaphore)
    L(vkCreateFence)
    L(vkDestroyFence)
    L(vkResetFences)
    L(vkWaitForFences)
    L(vkAcquireNextImageKHR)
    L(vkQueueSubmit)
    L(vkQueuePresentKHR)
    L(vkDeviceWaitIdle)
    L(vkFreeCommandBuffers)
#undef L
  }

  void Unload()
  {
    if (mod)
    {
      FreeLibrary(mod);
      mod = nullptr;
    }
  }
};

// Minimal SPIR-V: fullscreen-ish colored triangle via push constant color + hardcoded positions.
// Precompiled offline would be ideal; here we embed tiny hand-written SPIR-V for a solid color
// triangle generated by a known-good snippet.

// glsl: void main(){ vec2 p[3]=vec2[](vec2(0,-0.5),vec2(0.5,0.5),vec2(-0.5,0.5));
// gl_Position=vec4(p[gl_VertexIndex],0,1); }
// Simplified: use runtime vkCreateShaderModule with embedded SPIR-V bytes.

// clang-format off
static const uint32_t kVertSpv[] = {
  0x07230203,0x00010000,0x0008000b,0x0000001e,0x00000000,0x00020011,0x00000001,0x0006000b,
  0x00000001,0x4c534c47,0x6474732e,0x3035342e,0x00000000,0x0003000e,0x00000000,0x00000001,
  0x0007000f,0x00000000,0x00000004,0x6e69616d,0x00000000,0x0000000d,0x00000012,0x00030003,
  0x00000002,0x000001c2,0x00040005,0x00000004,0x6e69616d,0x00000000,0x00060005,0x0000000b,
  0x505f6c67,0x65567265,0x78657472,0x00000000,0x00060006,0x0000000b,0x00000000,0x505f6c67,
  0x7469736f,0x006e6f69,0x00070006,0x0000000b,0x00000001,0x505f6c67,0x746e696f,0x657a6953,
  0x00000000,0x00070006,0x0000000b,0x00000002,0x435f6c67,0x4470696c,0x61747369,0x0065636e,
  0x00070006,0x0000000b,0x00000003,0x435f6c67,0x446c6c75,0x61747369,0x0065636e,0x00030005,
  0x0000000d,0x00000000,0x00060005,0x00000012,0x565f6c67,0x65747265,0x646e4978,0x00007865,
  0x00050048,0x0000000b,0x00000000,0x0000000b,0x00000000,0x00050048,0x0000000b,0x00000001,
  0x0000000b,0x00000001,0x00050048,0x0000000b,0x00000002,0x0000000b,0x00000003,0x00050048,
  0x0000000b,0x00000003,0x0000000b,0x00000004,0x00030047,0x0000000b,0x00000002,0x00040047,
  0x00000012,0x0000000b,0x0000002a,0x00020013,0x00000002,0x00030021,0x00000003,0x00000002,
  0x00030016,0x00000006,0x00000020,0x00040017,0x00000007,0x00000006,0x00000004,0x00040015,
  0x00000008,0x00000020,0x00000000,0x0004002b,0x00000008,0x00000009,0x00000001,0x0004001c,
  0x0000000a,0x00000006,0x00000009,0x0006001e,0x0000000b,0x00000007,0x00000006,0x0000000a,
  0x0000000a,0x00040020,0x0000000c,0x00000003,0x0000000b,0x0004003b,0x0000000c,0x0000000d,
  0x00000003,0x00040015,0x0000000e,0x00000020,0x00000001,0x0004002b,0x0000000e,0x0000000f,
  0x00000000,0x00040020,0x00000010,0x00000001,0x0000000e,0x0004003b,0x00000010,0x00000012,
  0x00000001,0x0004002b,0x00000006,0x00000014,0x00000000,0x0004002b,0x00000006,0x00000015,
  0xbf000000,0x0004002b,0x00000006,0x00000018,0x3f000000,0x00050036,0x00000002,0x00000004,
  0x00000000,0x00000003,0x000200f8,0x00000005,0x0004003d,0x0000000e,0x00000013,0x00000012,
  0x00070050,0x00000007,0x0000001a,0x00000014,0x00000015,0x00000014,0x00000018,0x00070050,
  0x00000007,0x0000001b,0x00000018,0x00000018,0x00000014,0x00000018,0x00070050,0x00000007,
  0x0000001c,0x00000015,0x00000018,0x00000014,0x00000018,0x000300f7,0x0000001d,0x00000000,
  0x000400fa,0x00000013,0x0000001e,0x0000001f,0x000200f8,0x0000001e,0x00050041,0x00000020,
  0x00000021,0x0000000d,0x0000000f,0x0003003e,0x00000021,0x0000001a,0x000200f9,0x0000001d,
  0x000200f8,0x0000001f,0x000300f7,0x00000022,0x00000000,0x000400fa,0x00000013,0x00000023,
  0x00000024,0x000200f8,0x00000023,0x00050041,0x00000020,0x00000025,0x0000000d,0x0000000f,
  0x0003003e,0x00000025,0x0000001b,0x000200f9,0x00000022,0x000200f8,0x00000024,0x00050041,
  0x00000020,0x00000026,0x0000000d,0x0000000f,0x0003003e,0x00000026,0x0000001c,0x000200f9,
  0x00000022,0x000200f8,0x00000022,0x000200f9,0x0000001d,0x000200f8,0x0000001d,0x000100fd,
  0x00010038
};
// The above hand SPIR-V is fragile. Prefer a simpler approach: no vertex shader geometry —
// just clear color animation which still proves live capture. Frame counter via window title.
// clang-format on

// Actually hand-written SPIR-V above is incomplete/wrong. Use clear-only path + title frame
// counter which is enough for "frame counter advancing" if we update title. HUD text requires
// more. Better: use D3DCompile isn't available for SPIR-V.
//
// Practical approach for zero-SDK: clear color + update window title with frame number each
// frame so capture of the client still shows cycling color, and title shows the counter for
// window-capture tests. For game capture the clear color cycling is the live signal.

class VulkanRenderer final : public IRenderer
{
public:
  ~VulkanRenderer() override { Shutdown(); }

  bool Init(HWND hwnd, const Config& cfg, std::wstring* error) override
  {
    hwnd_ = hwnd;
    cfg_ = cfg;
    width_ = cfg.width > 0 ? cfg.width : 1280;
    height_ = cfg.height > 0 ? cfg.height : 720;

    if (!api_.Load())
    {
      *error = L"LoadLibrary(vulkan-1.dll) failed — install a Vulkan runtime";
      return false;
    }

    VkApplicationInfo app{};
    app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
    app.pApplicationName = "fakegame";
    app.apiVersion = VK_API_VERSION_1_1;

    const char* instExt[] = {VK_KHR_SURFACE_EXTENSION_NAME, VK_KHR_WIN32_SURFACE_EXTENSION_NAME};
    VkInstanceCreateInfo ici{};
    ici.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    ici.pApplicationInfo = &app;
    ici.enabledExtensionCount = 2;
    ici.ppEnabledExtensionNames = instExt;
    VkResult r = api_.vkCreateInstance(&ici, nullptr, &instance_);
    if (r != VK_SUCCESS)
    {
      *error = L"vkCreateInstance failed";
      return false;
    }
    api_.LoadInstance(instance_);

    VkWin32SurfaceCreateInfoKHR sci{};
    sci.sType = VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR;
    sci.hinstance = GetModuleHandleW(nullptr);
    sci.hwnd = hwnd_;
    r = api_.vkCreateWin32SurfaceKHR(instance_, &sci, nullptr, &surface_);
    if (r != VK_SUCCESS)
    {
      *error = L"vkCreateWin32SurfaceKHR failed";
      return false;
    }

    uint32_t devCount = 0;
    api_.vkEnumeratePhysicalDevices(instance_, &devCount, nullptr);
    if (!devCount)
    {
      *error = L"no Vulkan physical devices";
      return false;
    }
    std::vector<VkPhysicalDevice> devs(devCount);
    api_.vkEnumeratePhysicalDevices(instance_, &devCount, devs.data());
    phys_ = devs[0];

    uint32_t qCount = 0;
    api_.vkGetPhysicalDeviceQueueFamilyProperties(phys_, &qCount, nullptr);
    std::vector<VkQueueFamilyProperties> qprops(qCount);
    api_.vkGetPhysicalDeviceQueueFamilyProperties(phys_, &qCount, qprops.data());
    graphicsFamily_ = UINT32_MAX;
    for (uint32_t i = 0; i < qCount; ++i)
    {
      VkBool32 present = VK_FALSE;
      api_.vkGetPhysicalDeviceSurfaceSupportKHR(phys_, i, surface_, &present);
      if ((qprops[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) && present)
      {
        graphicsFamily_ = i;
        break;
      }
    }
    if (graphicsFamily_ == UINT32_MAX)
    {
      *error = L"no graphics+present queue family";
      return false;
    }

    float prio = 1.f;
    VkDeviceQueueCreateInfo qci{};
    qci.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
    qci.queueFamilyIndex = graphicsFamily_;
    qci.queueCount = 1;
    qci.pQueuePriorities = &prio;
    const char* devExt[] = {VK_KHR_SWAPCHAIN_EXTENSION_NAME};
    VkDeviceCreateInfo dci{};
    dci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
    dci.queueCreateInfoCount = 1;
    dci.pQueueCreateInfos = &qci;
    dci.enabledExtensionCount = 1;
    dci.ppEnabledExtensionNames = devExt;
    r = api_.vkCreateDevice(phys_, &dci, nullptr, &device_);
    if (r != VK_SUCCESS)
    {
      *error = L"vkCreateDevice failed";
      return false;
    }
    api_.vkGetDeviceQueue(device_, graphicsFamily_, 0, &queue_);

    if (!CreateSwapchain(error))
      return false;
    if (!CreateRenderPass(error))
      return false;
    if (!CreateFramebuffers(error))
      return false;
    if (!CreateCommands(error))
      return false;

    Log("vulkan: device ok swapchain %dx%d images=%u", width_, height_, (unsigned)images_.size());
    Log("vulkan: HUD is clear-color + title frame counter (minimal SPIR-V path)");
    return true;
  }

  void Shutdown() override
  {
    if (device_)
      api_.vkDeviceWaitIdle(device_);
    DestroySwapchainObjects();
    if (cmdPool_)
    {
      api_.vkDestroyCommandPool(device_, cmdPool_, nullptr);
      cmdPool_ = VK_NULL_HANDLE;
    }
    if (renderPass_)
    {
      api_.vkDestroyRenderPass(device_, renderPass_, nullptr);
      renderPass_ = VK_NULL_HANDLE;
    }
    if (device_)
    {
      api_.vkDestroyDevice(device_, nullptr);
      device_ = VK_NULL_HANDLE;
    }
    if (surface_)
    {
      api_.vkDestroySurfaceKHR(instance_, surface_, nullptr);
      surface_ = VK_NULL_HANDLE;
    }
    if (instance_)
    {
      api_.vkDestroyInstance(instance_, nullptr);
      instance_ = VK_NULL_HANDLE;
    }
    api_.Unload();
  }

  bool Resize(int width, int height, std::wstring* error) override
  {
    if (width < 1 || height < 1)
      return true;
    width_ = width;
    height_ = height;
    return RecreateSwapchain(error);
  }

  bool RecreateSwapchain(std::wstring* error) override
  {
    if (!device_)
      return true;
    api_.vkDeviceWaitIdle(device_);
    DestroySwapchainObjects();
    if (!CreateSwapchain(error))
      return false;
    if (!CreateFramebuffers(error))
      return false;
    // re-record command buffers next frame via rebuild
    cmdsDirty_ = true;
    return true;
  }

  bool RecreateDevice(std::wstring* error) override
  {
    Log("vulkan: recreating device");
    Config c = cfg_;
    HWND h = hwnd_;
    int w = width_, ht = height_;
    Shutdown();
    width_ = w;
    height_ = ht;
    return Init(h, c, error);
  }

  bool SetMode(WindowMode mode, std::wstring* error) override
  {
    (void)mode;
    (void)error;
    Log("vulkan: SetMode ignored (use borderless window styles)");
    return true;
  }

  void Render(const FrameInfo& info) override
  {
    if (!device_ || images_.empty())
      return;

    if (cmdsDirty_)
    {
      RecordCommands();
      cmdsDirty_ = false;
    }

    // Animate clear by re-recording each frame (simple, not optimal).
    RecordCommands(info);

    api_.vkWaitForFences(device_, 1, &inFlight_, VK_TRUE, UINT64_MAX);
    api_.vkResetFences(device_, 1, &inFlight_);

    uint32_t imageIndex = 0;
    VkResult ar = api_.vkAcquireNextImageKHR(device_, swapchain_, UINT64_MAX, imageAvailable_,
                                             VK_NULL_HANDLE, &imageIndex);
    if (ar == VK_ERROR_OUT_OF_DATE_KHR)
    {
      std::wstring err;
      RecreateSwapchain(&err);
      return;
    }

    VkPipelineStageFlags waitStage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    VkSubmitInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.waitSemaphoreCount = 1;
    si.pWaitSemaphores = &imageAvailable_;
    si.pWaitDstStageMask = &waitStage;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmdBufs_[imageIndex];
    si.signalSemaphoreCount = 1;
    si.pSignalSemaphores = &renderFinished_;
    api_.vkQueueSubmit(queue_, 1, &si, inFlight_);

    VkPresentInfoKHR pi{};
    pi.sType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR;
    pi.waitSemaphoreCount = 1;
    pi.pWaitSemaphores = &renderFinished_;
    pi.swapchainCount = 1;
    pi.pSwapchains = &swapchain_;
    pi.pImageIndices = &imageIndex;
    api_.vkQueuePresentKHR(queue_, &pi);

    // Frame counter in title so a frozen capture is obvious even without glyph atlas.
    if (!info.noHud && (info.frameIndex % 2) == 0)
    {
      wchar_t title[512];
      swprintf_s(title, L"%s | vk frame %llu | %s | %.1fs", info.windowTitle.c_str(),
                 (unsigned long long)info.frameIndex, info.sceneName ? info.sceneName : L"?",
                 info.elapsedSec);
      SetWindowTextW(hwnd_, title);
    }
  }

  const wchar_t* ApiName() const override { return L"vulkan"; }
  const wchar_t* SwapEffectName() const override { return L"FIFO/MAILBOX"; }
  const wchar_t* PresentModeName() const override
  {
    return cfg_.vsync ? L"FIFO" : L"MAILBOX/IMMEDIATE";
  }

private:
  void DestroySwapchainObjects()
  {
    if (device_ && !cmdBufs_.empty() && cmdPool_)
    {
      api_.vkFreeCommandBuffers(device_, cmdPool_, (uint32_t)cmdBufs_.size(), cmdBufs_.data());
      cmdBufs_.clear();
    }
    for (auto fb : framebuffers_)
      if (fb)
        api_.vkDestroyFramebuffer(device_, fb, nullptr);
    framebuffers_.clear();
    for (auto v : views_)
      if (v)
        api_.vkDestroyImageView(device_, v, nullptr);
    views_.clear();
    images_.clear();
    if (swapchain_)
    {
      api_.vkDestroySwapchainKHR(device_, swapchain_, nullptr);
      swapchain_ = VK_NULL_HANDLE;
    }
    if (imageAvailable_)
    {
      api_.vkDestroySemaphore(device_, imageAvailable_, nullptr);
      imageAvailable_ = VK_NULL_HANDLE;
    }
    if (renderFinished_)
    {
      api_.vkDestroySemaphore(device_, renderFinished_, nullptr);
      renderFinished_ = VK_NULL_HANDLE;
    }
    if (inFlight_)
    {
      api_.vkDestroyFence(device_, inFlight_, nullptr);
      inFlight_ = VK_NULL_HANDLE;
    }
  }

  bool CreateSwapchain(std::wstring* error)
  {
    VkSurfaceCapabilitiesKHR caps{};
    api_.vkGetPhysicalDeviceSurfaceCapabilitiesKHR(phys_, surface_, &caps);
    uint32_t fmtCount = 0;
    api_.vkGetPhysicalDeviceSurfaceFormatsKHR(phys_, surface_, &fmtCount, nullptr);
    std::vector<VkSurfaceFormatKHR> formats(fmtCount);
    api_.vkGetPhysicalDeviceSurfaceFormatsKHR(phys_, surface_, &fmtCount, formats.data());
    VkSurfaceFormatKHR fmt = formats[0];
    for (auto& f : formats)
      if (f.format == VK_FORMAT_B8G8R8A8_UNORM || f.format == VK_FORMAT_R8G8B8A8_UNORM)
      {
        fmt = f;
        break;
      }
    surfaceFormat_ = fmt;

    uint32_t pmCount = 0;
    api_.vkGetPhysicalDeviceSurfacePresentModesKHR(phys_, surface_, &pmCount, nullptr);
    std::vector<VkPresentModeKHR> pms(pmCount);
    api_.vkGetPhysicalDeviceSurfacePresentModesKHR(phys_, surface_, &pmCount, pms.data());
    presentMode_ = VK_PRESENT_MODE_FIFO_KHR;
    if (!cfg_.vsync)
    {
      for (auto pm : pms)
        if (pm == VK_PRESENT_MODE_MAILBOX_KHR)
        {
          presentMode_ = pm;
          break;
        }
      if (presentMode_ == VK_PRESENT_MODE_FIFO_KHR)
        for (auto pm : pms)
          if (pm == VK_PRESENT_MODE_IMMEDIATE_KHR)
          {
            presentMode_ = pm;
            break;
          }
    }

    if (caps.currentExtent.width != UINT32_MAX)
    {
      width_ = caps.currentExtent.width;
      height_ = caps.currentExtent.height;
    }
    uint32_t imgCount = caps.minImageCount + 1;
    if (caps.maxImageCount > 0 && imgCount > caps.maxImageCount)
      imgCount = caps.maxImageCount;

    VkSwapchainCreateInfoKHR ci{};
    ci.sType = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR;
    ci.surface = surface_;
    ci.minImageCount = imgCount;
    ci.imageFormat = fmt.format;
    ci.imageColorSpace = fmt.colorSpace;
    ci.imageExtent = {(uint32_t)width_, (uint32_t)height_};
    ci.imageArrayLayers = 1;
    ci.imageUsage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
    ci.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
    ci.preTransform = caps.currentTransform;
    ci.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
    ci.presentMode = presentMode_;
    ci.clipped = VK_TRUE;
    VkResult r = api_.vkCreateSwapchainKHR(device_, &ci, nullptr, &swapchain_);
    if (r != VK_SUCCESS)
    {
      *error = L"vkCreateSwapchainKHR failed";
      return false;
    }

    uint32_t n = 0;
    api_.vkGetSwapchainImagesKHR(device_, swapchain_, &n, nullptr);
    images_.resize(n);
    api_.vkGetSwapchainImagesKHR(device_, swapchain_, &n, images_.data());
    views_.resize(n);
    for (uint32_t i = 0; i < n; ++i)
    {
      VkImageViewCreateInfo vi{};
      vi.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
      vi.image = images_[i];
      vi.viewType = VK_IMAGE_VIEW_TYPE_2D;
      vi.format = fmt.format;
      vi.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
      vi.subresourceRange.levelCount = 1;
      vi.subresourceRange.layerCount = 1;
      r = api_.vkCreateImageView(device_, &vi, nullptr, &views_[i]);
      if (r != VK_SUCCESS)
      {
        *error = L"vkCreateImageView failed";
        return false;
      }
    }

    VkSemaphoreCreateInfo sei{VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO};
    api_.vkCreateSemaphore(device_, &sei, nullptr, &imageAvailable_);
    api_.vkCreateSemaphore(device_, &sei, nullptr, &renderFinished_);
    VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
    fi.flags = VK_FENCE_CREATE_SIGNALED_BIT;
    api_.vkCreateFence(device_, &fi, nullptr, &inFlight_);
    return true;
  }

  bool CreateRenderPass(std::wstring* error)
  {
    VkAttachmentDescription att{};
    att.format = surfaceFormat_.format;
    att.samples = VK_SAMPLE_COUNT_1_BIT;
    att.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
    att.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
    att.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    att.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    att.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    att.finalLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
    VkAttachmentReference ref{0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
    VkSubpassDescription sub{};
    sub.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
    sub.colorAttachmentCount = 1;
    sub.pColorAttachments = &ref;
    VkSubpassDependency dep{};
    dep.srcSubpass = VK_SUBPASS_EXTERNAL;
    dep.dstSubpass = 0;
    dep.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    dep.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    dep.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    VkRenderPassCreateInfo rp{};
    rp.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
    rp.attachmentCount = 1;
    rp.pAttachments = &att;
    rp.subpassCount = 1;
    rp.pSubpasses = &sub;
    rp.dependencyCount = 1;
    rp.pDependencies = &dep;
    if (api_.vkCreateRenderPass(device_, &rp, nullptr, &renderPass_) != VK_SUCCESS)
    {
      *error = L"vkCreateRenderPass failed";
      return false;
    }
    return true;
  }

  bool CreateFramebuffers(std::wstring* error)
  {
    framebuffers_.resize(views_.size());
    for (size_t i = 0; i < views_.size(); ++i)
    {
      VkFramebufferCreateInfo fi{};
      fi.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
      fi.renderPass = renderPass_;
      fi.attachmentCount = 1;
      fi.pAttachments = &views_[i];
      fi.width = width_;
      fi.height = height_;
      fi.layers = 1;
      if (api_.vkCreateFramebuffer(device_, &fi, nullptr, &framebuffers_[i]) != VK_SUCCESS)
      {
        *error = L"vkCreateFramebuffer failed";
        return false;
      }
    }
    return true;
  }

  bool CreateCommands(std::wstring* error)
  {
    VkCommandPoolCreateInfo pci{};
    pci.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
    pci.queueFamilyIndex = graphicsFamily_;
    pci.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    if (api_.vkCreateCommandPool(device_, &pci, nullptr, &cmdPool_) != VK_SUCCESS)
    {
      *error = L"vkCreateCommandPool failed";
      return false;
    }
    cmdBufs_.resize(images_.size());
    VkCommandBufferAllocateInfo ai{};
    ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    ai.commandPool = cmdPool_;
    ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    ai.commandBufferCount = (uint32_t)cmdBufs_.size();
    if (api_.vkAllocateCommandBuffers(device_, &ai, cmdBufs_.data()) != VK_SUCCESS)
    {
      *error = L"vkAllocateCommandBuffers failed";
      return false;
    }
    cmdsDirty_ = true;
    return true;
  }

  void RecordCommands(const FrameInfo& info = {})
  {
    const float t = float(info.elapsedSec);
    VkClearValue clear{};
    clear.color.float32[0] = 0.12f + 0.12f * std::sin(t * 1.7f);
    clear.color.float32[1] = 0.10f + 0.10f * std::sin(t * 1.3f + 2.f);
    clear.color.float32[2] = 0.18f + 0.14f * std::sin(t * 2.1f + 4.f);
    clear.color.float32[3] = 1.f;
    // Moving accent: pulse alpha of clear green channel harder so freeze is obvious.
    clear.color.float32[1] += 0.25f * (0.5f + 0.5f * std::sin(t * 8.f));

    for (size_t i = 0; i < cmdBufs_.size(); ++i)
    {
      VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
      api_.vkBeginCommandBuffer(cmdBufs_[i], &bi);
      VkRenderPassBeginInfo rp{};
      rp.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
      rp.renderPass = renderPass_;
      rp.framebuffer = framebuffers_[i];
      rp.renderArea.extent = {(uint32_t)width_, (uint32_t)height_};
      rp.clearValueCount = 1;
      rp.pClearValues = &clear;
      api_.vkCmdBeginRenderPass(cmdBufs_[i], &rp, VK_SUBPASS_CONTENTS_INLINE);
      api_.vkCmdEndRenderPass(cmdBufs_[i]);
      api_.vkEndCommandBuffer(cmdBufs_[i]);
    }
  }

  VkApi api_{};
  HWND hwnd_ = nullptr;
  Config cfg_{};
  int width_ = 0, height_ = 0;
  VkInstance instance_ = VK_NULL_HANDLE;
  VkSurfaceKHR surface_ = VK_NULL_HANDLE;
  VkPhysicalDevice phys_ = VK_NULL_HANDLE;
  VkDevice device_ = VK_NULL_HANDLE;
  VkQueue queue_ = VK_NULL_HANDLE;
  uint32_t graphicsFamily_ = 0;
  VkSwapchainKHR swapchain_ = VK_NULL_HANDLE;
  VkSurfaceFormatKHR surfaceFormat_{};
  VkPresentModeKHR presentMode_ = VK_PRESENT_MODE_FIFO_KHR;
  std::vector<VkImage> images_;
  std::vector<VkImageView> views_;
  std::vector<VkFramebuffer> framebuffers_;
  VkRenderPass renderPass_ = VK_NULL_HANDLE;
  VkCommandPool cmdPool_ = VK_NULL_HANDLE;
  std::vector<VkCommandBuffer> cmdBufs_;
  VkSemaphore imageAvailable_ = VK_NULL_HANDLE;
  VkSemaphore renderFinished_ = VK_NULL_HANDLE;
  VkFence inFlight_ = VK_NULL_HANDLE;
  bool cmdsDirty_ = true;
};

} // namespace

std::unique_ptr<IRenderer> CreateVulkanRenderer()
{
  return std::make_unique<VulkanRenderer>();
}
